/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit)
    testImplementation(libs.test.parameter.injector)

    compileOnlyApi(libs.auto.value.annotations)
    annotationProcessor(libs.auto.value)

    implementation(libs.antlr4.runtime)
    implementation(libs.guava)
    implementation(libs.jspecify)
    implementation(libs.protobuf.java)
    implementation(libs.protobuf.java.util)
    implementation(libs.re2j)
    implementation(project(":generated"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
