load("@rules_java//java:defs.bzl", "java_library")
load("//:testing.bzl", "junit4_test_suites")

package(
    default_applicable_licenses = ["//:license"],
)

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    deps = [
        "//:java_truth",
        "//bundle:cel",
        "//common:cel_ast",
        "//common:cel_exception",
        "//common:cel_function_decl",
        "//common:cel_overload_decl",
        "//common:cel_validation_exception",
        "//common:cel_validation_result",
        "//common:cel_var_decl",
        "//common:container",
        "//common:options",
        "//common/ast",
        "//common/exceptions:attribute_not_found",
        "//common/exceptions:divide_by_zero",
        "//common/exceptions:index_out_of_bounds",
        "//common/exceptions:invalid_argument",
        "//common/types",
        "//common/types:type_providers",
        "//common/values",
        "//common/values:cel_byte_string",
        "//common/values:cel_value_provider",
        "//compiler",
        "//compiler:compiler_builder",
        "//extensions",
        "//extensions:extension_library",
        "//extensions:lite_extensions",
        "//extensions:math",
        "//extensions:math_compiler_library",
        "//extensions:math_runtime_library",
        "//extensions:native",
        "//extensions:optional_library",
        "//extensions:sets",
        "//extensions:sets_function",
        "//extensions:strings",
        "//parser:macro",
        "//parser:unparser",
        "//runtime",
        "//runtime:function_binding",
        "//runtime:lite_runtime",
        "//runtime:lite_runtime_factory",
        "//runtime:partial_vars",
        "//runtime:unknown_attributes",
        "//testing:cel_runtime_flavor",
        "//validator",
        "//validator:validator_builder",
        "//validator/validators:homogeneous_literal",
        "@cel_spec//proto/cel/expr/conformance/proto2:test_all_types_java_proto",
        "@cel_spec//proto/cel/expr/conformance/proto3:test_all_types_java_proto",
        "@cel_spec//proto/cel/expr/conformance/test:simple_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:junit_junit",
    ],
)

junit4_test_suites(
    name = "test_suites",
    sizes = [
        "small",
    ],
    src_dir = "src/test/java",
    deps = [":tests"],
)
